AWSTemplateFormatVersion: "2010-09-09"

Description: Notes app

Parameters:
  Deployment:
    Description: Name of the deployment (prod/dev/etc.)
    Type: String
    Default: dev
  Version:
    Description: Immutable version name (git commit hash)
    Type: String
  DBPassword: 
    Description: Database password
    Type: String
    Default: xyzzyzyx

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  NotesList:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "app.list_notes"
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Code:
        S3Bucket: notes-artifacts
        S3Key: !Join [ "", ["app-", !Ref Version, ".zip"] ]
      Runtime: "python3.6"
      Timeout: "3"

#Outputs:

