AWSTemplateFormatVersion: "2010-09-09"

Description: Notes infrastructure

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
    DeletionPolicy: Retain

Outputs:
  ArtifactBucket:
    Description: Name of the S3 bucket for artifacts
    Value: !Ref ArtifactBucket
    Export:
      Name: NotesArtifactBucket
