AWSTemplateFormatVersion: "2010-09-09"

Description: Notes infrastructure

Parameters:
  DBPassword: 
    Description: Database password
    Type: String
    Default: xyzzy

Resources:
  NotesDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.m1.small
      DBSecurityGroups:
        - Ref: NotesDbSecurityGroup
      Engine: MySQL
      MasterUsername: master
      MasterUserPassword: !Ref DBPassword
    DeletionPolicy: Snapshot

  NotesDbSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties: 
      GroupDescription: Ingress for Amazon EC2 security group
      EC2VpcId:
        Ref: MyVPC
      DBSecurityGroupIngress:
        - EC2SecurityGroupId: sg-b0ff1111
          EC2SecurityGroupOwnerId: '111122223333'
        - EC2SecurityGroupId: sg-ffd722222
          EC2SecurityGroupOwnerId: '111122223333'



Outputs:
  DBAddress:
    Description: DB Endpoint address
    Value: !GetAtt Endpoint.Address
    Export:
      Name: NotesDBAddress

  DBPort:
    Description: DB Endpoint port
    Value: !GetAtt Endpoint.Port
    Export:
      Name: NotesDBPort

