AWSTemplateFormatVersion: "2010-09-09"

Description: Notes infrastructure

Parameters:
  DBPassword: 
    Description: Database password
    Type: String
    Default: xyzzyxyz

Resources:
  NotesDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      #DBSecurityGroups:
      #  - Ref: NotesDbSecurityGroup
      Engine: MySQL
      MasterUsername: master
      MasterUserPassword: !Ref DBPassword
    DeletionPolicy: Snapshot

Outputs:
  DBAddress:
    Description: DB Endpoint address
    Value: !GetAtt NotesDB.Endpoint.Address
    Export:
      Name: NotesDBAddress

  DBPort:
    Description: DB Endpoint port
    Value: !GetAtt NotesDB.Endpoint.Port
    Export:
      Name: NotesDBPort


#  NotesDbSecurityGroup:
#    Type: AWS::RDS::DBSecurityGroup
#    Properties:
#      GroupDescription: Ingress for Amazon EC2 security group
#      EC2VpcId: vpc-f1509598
#        #Ref: MyVPC
#      DBSecurityGroupIngress:
#        - EC2SecurityGroupId: sg-b0ff1111
#          EC2SecurityGroupOwnerId: '111122223333'
#        - EC2SecurityGroupId: sg-ffd722222
#          EC2SecurityGroupOwnerId: '111122223333'
